/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2_final_enrique_tebalanss2024.Fronted;
import com.mycompany.proyecto2_final_enrique_tebalanss2024.Backend.gestorArchivos;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import com.mycompany.proyecto2_final_enrique_tebalanss2024.Fronted.MenuAcercaDe;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;


import com.mycompany.proyecto2_final_enrique_tebalanss2024.Fronted.MenuJugadorVsJugador;
import java.io.File;
import java.io.FileWriter;
/**
 *
 * @author DELL
 */
public class MenuBienvenida extends javax.swing.JFrame {

    /**
     * Creates new form MenuBienvenida
     */
    public MenuBienvenida() {
        initComponents();
       // ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/0.JPG"));
       // imagencero.setIcon(new ImageIcon(getClass().getResource("/imagenes/0.JPG")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AccionCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        AccionAcercaDe = new javax.swing.JButton();
        accionJugarIA = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("¡ BIENVENID@ !");

        AccionCerrar.setBackground(new java.awt.Color(255, 102, 102));
        AccionCerrar.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        AccionCerrar.setForeground(new java.awt.Color(0, 0, 0));
        AccionCerrar.setText("CERRAR");
        AccionCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionCerrarActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("POCKTALE MONSTER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addComponent(AccionCerrar)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccionCerrar)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        AccionAcercaDe.setBackground(new java.awt.Color(51, 255, 0));
        AccionAcercaDe.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        AccionAcercaDe.setForeground(new java.awt.Color(0, 0, 0));
        AccionAcercaDe.setText("ACERCA DE");
        AccionAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionAcercaDeActionPerformed(evt);
            }
        });

        accionJugarIA.setBackground(new java.awt.Color(0, 255, 0));
        accionJugarIA.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        accionJugarIA.setForeground(new java.awt.Color(0, 0, 0));
        accionJugarIA.setText("JUGAR VS IA");
        accionJugarIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionJugarIAActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\OneDrive\\Documentos\\NetBeansProjects\\Proyecto2_Final_Enrique_TebalanSS2024\\src\\main\\resources\\imagenes\\pokemon.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(accionJugarIA)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(AccionAcercaDe)
                                .addGap(20, 20, 20)))
                        .addGap(240, 240, 240))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(accionJugarIA)
                .addGap(18, 18, 18)
                .addComponent(AccionAcercaDe)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccionCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionCerrarActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea cerrar el juego?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION)
            {
            this.dispose();
            gestorArchivos archivo = new gestorArchivos();
            archivo.limpiarArchivo();
            System.exit(0);
            }
    }//GEN-LAST:event_AccionCerrarActionPerformed
    
    
         private String fecha(){
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
        
    }
    public int hora,minutos,segundos;
    
    private int hora(){ 
      Calendar calendario = new GregorianCalendar();
      hora= calendario.get(Calendar.HOUR_OF_DAY);
      minutos = calendario.get(Calendar.MINUTE);
      segundos = calendario.get(Calendar.SECOND);
      //lblhora.setText(hora + ":" + minutos + ":" + segundos);   
      return hora;
    }
    
    private int minutos()
    {
        Calendar calendario = new GregorianCalendar();
        minutos = calendario.get(Calendar.MINUTE);
        return minutos;
    }
    
    private int segundos()
    {
        Calendar calendario = new GregorianCalendar();
        segundos = calendario.get(Calendar.SECOND);
        return segundos;
    }
    private void AccionAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionAcercaDeActionPerformed
        // TODO add your handling code here:
        this.dispose();
       int hora = hora();
       int minutos = minutos();
       int segundos = segundos();
        gestorArchivos archivo = new gestorArchivos();
        archivo.conectarConCarpeta();
        archivo.escribirEnArchivoDeTexto("-------------------------------------------------------------");
        archivo.escribirEnArchivoDeTexto("NOMBRE JUGADOR 1:"+"WILLIAM");
        archivo.escribirEnArchivoDeTexto("NOMBRE JUGADOR 2:"+""+"\n"); //ACA CAMBIAR ESO
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String fechaFormateada = formatofecha.format(new Date());
        archivo.escribirEnArchivoDeTexto("-          Fecha: " + fechaFormateada+"\n");
        archivo.escribirEnArchivoDeTexto("NOMBRE DEL SOFTWARE: APACHE NETBEANS       -"+ "VERSION DEL SOFTWARE: IDE 22   "+"\n");
        archivo.escribirEnArchivoDeTexto("DESCRIPCION DEL SOFTWARE: Es un entorno de programacion en donde se desarrolla software"+"\n");
        archivo.escribirEnArchivoDeTexto("NOMBRE DEL DESARROLLADOR: KIK3.H      -"+ "-    LUGAR Y AÑO DE DESARROLLO: QUETZALTENANGO 2024");
        archivo.escribirEnArchivoDeTexto("-------------------------------------------------------------"+"\n");
        
        MenuAcercaDe menu2 = new MenuAcercaDe();
        menu2.setTitle("MENU ACERCA DE");
        menu2.setLocationRelativeTo(null);
        menu2.setVisible(true);
    }//GEN-LAST:event_AccionAcercaDeActionPerformed

    private void accionJugarIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionJugarIAActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MenuJugadorVsJugador menu3 = new MenuJugadorVsJugador();
        menu3.setTitle("MENU JUGADOR VS JUGADOR");
        menu3.setLocationRelativeTo(null);
        menu3.setVisible(true);
    }//GEN-LAST:event_accionJugarIAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MenuBienvenida().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccionAcercaDe;
    private javax.swing.JButton AccionCerrar;
    private javax.swing.JButton accionJugarIA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
