/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2_final_enrique_tebalanss2024.Fronted;

import com.mycompany.proyecto2_final_enrique_tebalanss2024.Backend.CrearCartas;
import com.mycompany.proyecto2_final_enrique_tebalanss2024.Backend.Jugador;
import com.mycompany.proyecto2_final_enrique_tebalanss2024.Backend.Mazo;
import com.mycompany.proyecto2_final_enrique_tebalanss2024.Backend.NombreJugador;
import com.mycompany.proyecto2_final_enrique_tebalanss2024.Fronted.MenuBienvenida;
import java.util.Random;

import javax.swing.JOptionPane;
/**
 *
 * @author DELL
 */

public class MenuJugadorVsJugador extends javax.swing.JFrame {
    private CrearCartas crearCartas;
    /**
     * Creates new form MenuJugadorVsJugador
     */
    public MenuJugadorVsJugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        accionRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        accionCerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreJugador = new javax.swing.JTextField();
        TirarMoneda = new javax.swing.JButton();
        CrearMazoJugador1 = new javax.swing.JButton();
        EditarMazoJugador1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        modoTontoIA = new javax.swing.JButton();
        modoInteligenteIA = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        GuardarNombreAccion = new javax.swing.JButton();
        mostrarnombre = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        accionRegresar.setBackground(new java.awt.Color(255, 204, 51));
        accionRegresar.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        accionRegresar.setForeground(new java.awt.Color(0, 0, 0));
        accionRegresar.setText("REGRESAR");
        accionRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionRegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("JUGADOR VS IA ");

        accionCerrar.setBackground(new java.awt.Color(255, 0, 0));
        accionCerrar.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        accionCerrar.setForeground(new java.awt.Color(0, 0, 0));
        accionCerrar.setText("CERRAR");
        accionCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accionRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(90, 90, 90)
                .addComponent(accionCerrar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(accionRegresar)
                        .addComponent(accionCerrar))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("INGRESA NOMBRE DE JUGADOR:");

        nombreJugador.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        nombreJugador.setForeground(new java.awt.Color(0, 0, 0));
        nombreJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreJugadorActionPerformed(evt);
            }
        });

        TirarMoneda.setBackground(new java.awt.Color(51, 255, 0));
        TirarMoneda.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        TirarMoneda.setForeground(new java.awt.Color(0, 0, 0));
        TirarMoneda.setText("CONTINUAR");
        TirarMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TirarMonedaActionPerformed(evt);
            }
        });

        CrearMazoJugador1.setBackground(new java.awt.Color(51, 255, 0));
        CrearMazoJugador1.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        CrearMazoJugador1.setForeground(new java.awt.Color(0, 0, 0));
        CrearMazoJugador1.setText("1. CREAR MAZO");
        CrearMazoJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearMazoJugador1ActionPerformed(evt);
            }
        });

        EditarMazoJugador1.setBackground(new java.awt.Color(51, 255, 0));
        EditarMazoJugador1.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        EditarMazoJugador1.setForeground(new java.awt.Color(0, 0, 0));
        EditarMazoJugador1.setText("EDITAR MAZO");
        EditarMazoJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarMazoJugador1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("MODO DE LA IA AL JUGAR:");

        modoTontoIA.setBackground(new java.awt.Color(51, 255, 51));
        modoTontoIA.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        modoTontoIA.setForeground(new java.awt.Color(0, 0, 0));
        modoTontoIA.setText("TONTO");
        modoTontoIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoTontoIAActionPerformed(evt);
            }
        });

        modoInteligenteIA.setBackground(new java.awt.Color(51, 255, 51));
        modoInteligenteIA.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        modoInteligenteIA.setForeground(new java.awt.Color(0, 0, 0));
        modoInteligenteIA.setText("INTELIGENTE");
        modoInteligenteIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoInteligenteIAActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("PRIMERO DEBES DE CREAR TU MAZO Y LUEGO TIRAS LA MONEDA :D");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes2/bulbasaur1.png"))); // NOI18N

        GuardarNombreAccion.setBackground(new java.awt.Color(51, 255, 51));
        GuardarNombreAccion.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        GuardarNombreAccion.setForeground(new java.awt.Color(0, 0, 0));
        GuardarNombreAccion.setText("GUARDAR NOMBRE");
        GuardarNombreAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarNombreAccionActionPerformed(evt);
            }
        });

        mostrarnombre.setForeground(new java.awt.Color(0, 0, 0));

        jButton2.setText("jButton2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(GuardarNombreAccion)
                                        .addGap(129, 129, 129)
                                        .addComponent(mostrarnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGap(120, 120, 120)
                                                .addComponent(modoTontoIA))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGap(66, 66, 66)
                                                .addComponent(modoInteligenteIA))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(CrearMazoJugador1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(EditarMazoJugador1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TirarMoneda)))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modoTontoIA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modoInteligenteIA)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(6, 6, 6)))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuardarNombreAccion)
                    .addComponent(mostrarnombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CrearMazoJugador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditarMazoJugador1)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TirarMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accionRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionRegresarActionPerformed
        // TODO add your handling code here:
     this.dispose();
     MenuBienvenida menu1 = new MenuBienvenida();
     menu1.setTitle("MENU BIENVENIDA");
     menu1.setLocationRelativeTo(null);
     menu1.setVisible(true);
    }//GEN-LAST:event_accionRegresarActionPerformed

    private void accionCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionCerrarActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea cerrar el juego?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION)
            {
            this.dispose();
            System.exit(0);
            }
    }//GEN-LAST:event_accionCerrarActionPerformed

    private void CrearMazoJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearMazoJugador1ActionPerformed
        // TODO add your handling code here:
        
     this.dispose();
     CrearCartas crearCartas = new CrearCartas();
     CrearMazoJugador1 menu4 = new CrearMazoJugador1(crearCartas);
     menu4.setTitle("MENU CREAR MAZO");
     menu4.setLocationRelativeTo(null);
     menu4.setVisible(true);
        
    }//GEN-LAST:event_CrearMazoJugador1ActionPerformed

    private void EditarMazoJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarMazoJugador1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
     EditarMazoJugador1 menu4 = new EditarMazoJugador1();
     menu4.setTitle("MENU EDITAR MAZO");
     menu4.setLocationRelativeTo(null);
     menu4.setVisible(true);
     
    }//GEN-LAST:event_EditarMazoJugador1ActionPerformed

    private void TirarMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TirarMonedaActionPerformed
            // TODO add your handling code here:
      
        this.dispose();
     MenuPrepararPartida menu4 = new MenuPrepararPartida();
     menu4.setTitle("MENU PREPARAR PARTIDA");
     menu4.setLocationRelativeTo(null);
     menu4.setVisible(true);
    }//GEN-LAST:event_TirarMonedaActionPerformed

    private void modoTontoIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoTontoIAActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null, "CREAR EN EL BACK LA CARACTERISTICA IA TONTA \n");
    }//GEN-LAST:event_modoTontoIAActionPerformed

    private void nombreJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreJugadorActionPerformed
        // TODO add your handling code here:


        
    }//GEN-LAST:event_nombreJugadorActionPerformed

    private void modoInteligenteIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoInteligenteIAActionPerformed
            // TODO add your handling code here:
            JOptionPane.showMessageDialog(null, "CREAR EN EL BACK LA CARACTERISTICA IA INTELIGENTE \n");
    }//GEN-LAST:event_modoInteligenteIAActionPerformed
    public String nombreEnviar;
    private void GuardarNombreAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarNombreAccionActionPerformed
        // TODO add your handling code here:
        nombreEnviar = nombreJugador.getText();
       NombreJugador Jugador = new NombreJugador(nombreEnviar); // Crea el jugador con el nombre ingresado
       
       if (!nombreEnviar.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "El nombre ingresado fue: " + Jugador.getNombre());
        } else {
        JOptionPane.showMessageDialog(this, "Por favor ingresa un nombre válido.");
    }   
        mostrarnombre.setText("Nombre ingresado: " + Jugador.getNombre());
    }//GEN-LAST:event_GuardarNombreAccionActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String valor = JOptionPane.showInputDialog(null);
        cambiarImagen(jLabel5, valor);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cambiarImagen(javax.swing.JLabel label, String ruta) {
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(ruta)));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJugadorVsJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJugadorVsJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJugadorVsJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJugadorVsJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJugadorVsJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearMazoJugador1;
    private javax.swing.JButton EditarMazoJugador1;
    private javax.swing.JButton GuardarNombreAccion;
    private javax.swing.JButton TirarMoneda;
    private javax.swing.JButton accionCerrar;
    private javax.swing.JButton accionRegresar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton modoInteligenteIA;
    private javax.swing.JButton modoTontoIA;
    private javax.swing.JLabel mostrarnombre;
    private javax.swing.JTextField nombreJugador;
    // End of variables declaration//GEN-END:variables
}
