/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2_final_enrique_tebalanss2024.Fronted;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class PartidaMenu extends javax.swing.JFrame {

    /**
     * Creates new form PartidaMenu
     */
    public PartidaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AccionCargarPartida = new javax.swing.JButton();
        energiaAgregar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        bancaIA1 = new javax.swing.JLabel();
        descartadasIA = new javax.swing.JLabel();
        pilaIA1 = new javax.swing.JLabel();
        bancaIA2 = new javax.swing.JLabel();
        bancaIA3 = new javax.swing.JLabel();
        bancaIA4 = new javax.swing.JLabel();
        premioJG1 = new javax.swing.JLabel();
        premioIA2 = new javax.swing.JLabel();
        premioIA3 = new javax.swing.JLabel();
        cartaActualIA = new javax.swing.JLabel();
        cartaActualJugador = new javax.swing.JLabel();
        bancaJG1 = new javax.swing.JLabel();
        bancaJG2 = new javax.swing.JLabel();
        bancaJG3 = new javax.swing.JLabel();
        bancaJG4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        descartadasJG = new javax.swing.JLabel();
        pilaJG = new javax.swing.JLabel();
        premioIA1 = new javax.swing.JLabel();
        premioJG2 = new javax.swing.JLabel();
        premioJG3 = new javax.swing.JLabel();
        AccionAtacar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nombreTurnoActual = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        verMazoIA = new javax.swing.JButton();
        verMazoJG1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AccionRegresar = new javax.swing.JButton();
        AccionCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        AccionCargarPartida.setBackground(new java.awt.Color(0, 255, 0));
        AccionCargarPartida.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        AccionCargarPartida.setForeground(new java.awt.Color(0, 0, 0));
        AccionCargarPartida.setText("CARGAR PARTIDA");

        energiaAgregar.setBackground(new java.awt.Color(0, 255, 0));
        energiaAgregar.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        energiaAgregar.setForeground(new java.awt.Color(0, 0, 0));
        energiaAgregar.setText("AGREGAR ENERGIA");

        jButton3.setBackground(new java.awt.Color(0, 255, 0));
        jButton3.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("JUGAR HECHIZO");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        bancaIA1.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        bancaIA1.setForeground(new java.awt.Color(0, 0, 0));
        bancaIA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bancaIA1.setText("BANCA IA");
        bancaIA1.setToolTipText("");
        bancaIA1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        descartadasIA.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        descartadasIA.setForeground(new java.awt.Color(0, 0, 0));
        descartadasIA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descartadasIA.setText("DESCARTADAS");
        descartadasIA.setToolTipText("");
        descartadasIA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pilaIA1.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        pilaIA1.setForeground(new java.awt.Color(0, 0, 0));
        pilaIA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pilaIA1.setText("PILA DE CARTAS");
        pilaIA1.setToolTipText("");
        pilaIA1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bancaIA2.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        bancaIA2.setForeground(new java.awt.Color(0, 0, 0));
        bancaIA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bancaIA2.setText("BANCA IA");
        bancaIA2.setToolTipText("");
        bancaIA2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bancaIA3.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        bancaIA3.setForeground(new java.awt.Color(0, 0, 0));
        bancaIA3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bancaIA3.setText("BANCA IA");
        bancaIA3.setToolTipText("");
        bancaIA3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bancaIA4.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        bancaIA4.setForeground(new java.awt.Color(0, 0, 0));
        bancaIA4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bancaIA4.setText("BANCA IA");
        bancaIA4.setToolTipText("");
        bancaIA4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        premioJG1.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        premioJG1.setForeground(new java.awt.Color(0, 0, 0));
        premioJG1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        premioJG1.setText("CARTA PREMIO1");
        premioJG1.setToolTipText("");
        premioJG1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        premioIA2.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        premioIA2.setForeground(new java.awt.Color(0, 0, 0));
        premioIA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        premioIA2.setText("CARTA PREMIO1");
        premioIA2.setToolTipText("");
        premioIA2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        premioIA3.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        premioIA3.setForeground(new java.awt.Color(0, 0, 0));
        premioIA3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        premioIA3.setText("CARTA PREMIO1");
        premioIA3.setToolTipText("");
        premioIA3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cartaActualIA.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        cartaActualIA.setForeground(new java.awt.Color(0, 0, 0));
        cartaActualIA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartaActualIA.setText("ACTIVA IA");
        cartaActualIA.setToolTipText("");
        cartaActualIA.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        cartaActualJugador.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        cartaActualJugador.setForeground(new java.awt.Color(0, 0, 0));
        cartaActualJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartaActualJugador.setText("ACTIVA JG");
        cartaActualJugador.setToolTipText("");
        cartaActualJugador.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        bancaJG1.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        bancaJG1.setForeground(new java.awt.Color(0, 0, 0));
        bancaJG1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bancaJG1.setText("BANCA JG");
        bancaJG1.setToolTipText("");
        bancaJG1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bancaJG2.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        bancaJG2.setForeground(new java.awt.Color(0, 0, 0));
        bancaJG2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bancaJG2.setText("BANCA JG");
        bancaJG2.setToolTipText("");
        bancaJG2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bancaJG3.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        bancaJG3.setForeground(new java.awt.Color(0, 0, 0));
        bancaJG3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bancaJG3.setText("BANCA JG");
        bancaJG3.setToolTipText("");
        bancaJG3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bancaJG4.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        bancaJG4.setForeground(new java.awt.Color(0, 0, 0));
        bancaJG4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bancaJG4.setText("BANCA JG");
        bancaJG4.setToolTipText("");
        bancaJG4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        descartadasJG.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        descartadasJG.setForeground(new java.awt.Color(0, 0, 0));
        descartadasJG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descartadasJG.setText("DESCARTADAS");
        descartadasJG.setToolTipText("");
        descartadasJG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pilaJG.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        pilaJG.setForeground(new java.awt.Color(0, 0, 0));
        pilaJG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pilaJG.setText("PILA DE CARTAS");
        pilaJG.setToolTipText("");
        pilaJG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        premioIA1.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        premioIA1.setForeground(new java.awt.Color(0, 0, 0));
        premioIA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        premioIA1.setText("CARTA PREMIO1");
        premioIA1.setToolTipText("");
        premioIA1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        premioJG2.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        premioJG2.setForeground(new java.awt.Color(0, 0, 0));
        premioJG2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        premioJG2.setText("CARTA PREMIO1");
        premioJG2.setToolTipText("");
        premioJG2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        premioJG3.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        premioJG3.setForeground(new java.awt.Color(0, 0, 0));
        premioJG3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        premioJG3.setText("CARTA PREMIO1");
        premioJG3.setToolTipText("");
        premioJG3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AccionAtacar.setBackground(new java.awt.Color(0, 255, 0));
        AccionAtacar.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        AccionAtacar.setForeground(new java.awt.Color(0, 0, 0));
        AccionAtacar.setText("ATACAR");

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("TURNO DE:");

        nombreTurnoActual.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        nombreTurnoActual.setForeground(new java.awt.Color(0, 0, 0));
        nombreTurnoActual.setText("(nombre)");

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("TIEMPO DEL RIVAL:");

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("TIEMPO DEL JUGADOR:");

        jLabel5.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("TEMPORIZADOR");

        jLabel6.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("POR JUGADA:");

        jLabel7.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("(TIEMPO)");

        verMazoIA.setBackground(new java.awt.Color(0, 255, 0));
        verMazoIA.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        verMazoIA.setForeground(new java.awt.Color(0, 0, 0));
        verMazoIA.setText("VER MAZO");

        verMazoJG1.setBackground(new java.awt.Color(0, 255, 0));
        verMazoJG1.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        verMazoJG1.setForeground(new java.awt.Color(0, 0, 0));
        verMazoJG1.setText("VER MAZO");

        jLabel8.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("VS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccionCargarPartida)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(energiaAgregar)
                                    .addComponent(jButton3)
                                    .addComponent(AccionAtacar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 1, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(premioJG1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(premioJG2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pilaIA1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(descartadasIA, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(premioJG3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(bancaJG1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bancaJG2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bancaJG3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bancaJG4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(bancaIA1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(bancaIA2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(bancaIA3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(bancaIA4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(101, 101, 101)
                                                        .addComponent(jLabel8)
                                                        .addGap(128, 128, 128)
                                                        .addComponent(jLabel5)))))
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(verMazoIA))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(verMazoJG1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreTurnoActual)
                                .addGap(44, 44, 44))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(cartaActualIA, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(cartaActualJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(premioIA2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(premioIA3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descartadasJG, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(premioIA1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pilaJG, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(AccionCargarPartida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(energiaAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(AccionAtacar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bancaIA1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bancaIA2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bancaIA3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bancaIA4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pilaIA1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descartadasIA, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(premioJG1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(premioJG2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(premioJG3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(cartaActualJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(9, 9, 9)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(nombreTurnoActual))
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel4))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(cartaActualIA, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addGap(46, 46, 46))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(83, 83, 83)))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bancaJG1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bancaJG2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bancaJG3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bancaJG4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(premioIA1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verMazoIA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(premioIA2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(premioIA3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(descartadasJG, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pilaJG, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(verMazoJG1)
                                .addGap(72, 72, 72))))))
        );

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("POCKETALE MONSTER - PARTIDA");

        AccionRegresar.setBackground(new java.awt.Color(255, 204, 51));
        AccionRegresar.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        AccionRegresar.setForeground(new java.awt.Color(0, 0, 0));
        AccionRegresar.setText("REGRESAR");
        AccionRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionRegresarActionPerformed(evt);
            }
        });

        AccionCerrar.setBackground(new java.awt.Color(255, 0, 0));
        AccionCerrar.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        AccionCerrar.setForeground(new java.awt.Color(0, 0, 0));
        AccionCerrar.setText("CERRAR");
        AccionCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AccionRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(AccionCerrar)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccionCerrar)
                    .addComponent(AccionRegresar)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccionRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
     MenuPrepararPartida menu1 = new MenuPrepararPartida();
     menu1.setTitle("MENU PREPARAR PARTIDA");
     menu1.setLocationRelativeTo(null);
     menu1.setVisible(true);
    }//GEN-LAST:event_AccionRegresarActionPerformed

    private void AccionCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionCerrarActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea cerrar el juego?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION)
            {
            this.dispose();
            System.exit(0);
            }
    }//GEN-LAST:event_AccionCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartidaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartidaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartidaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartidaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartidaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccionAtacar;
    private javax.swing.JButton AccionCargarPartida;
    private javax.swing.JButton AccionCerrar;
    private javax.swing.JButton AccionRegresar;
    private javax.swing.JLabel bancaIA1;
    private javax.swing.JLabel bancaIA2;
    private javax.swing.JLabel bancaIA3;
    private javax.swing.JLabel bancaIA4;
    private javax.swing.JLabel bancaJG1;
    private javax.swing.JLabel bancaJG2;
    private javax.swing.JLabel bancaJG3;
    private javax.swing.JLabel bancaJG4;
    private javax.swing.JLabel cartaActualIA;
    private javax.swing.JLabel cartaActualJugador;
    private javax.swing.JLabel descartadasIA;
    private javax.swing.JLabel descartadasJG;
    private javax.swing.JButton energiaAgregar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nombreTurnoActual;
    private javax.swing.JLabel pilaIA1;
    private javax.swing.JLabel pilaJG;
    private javax.swing.JLabel premioIA1;
    private javax.swing.JLabel premioIA2;
    private javax.swing.JLabel premioIA3;
    private javax.swing.JLabel premioJG1;
    private javax.swing.JLabel premioJG2;
    private javax.swing.JLabel premioJG3;
    private javax.swing.JButton verMazoIA;
    private javax.swing.JButton verMazoJG1;
    // End of variables declaration//GEN-END:variables
}
